### ISSUE TITLE
Not compatible with 06-06 snapshot of Swift 3.0

### ISSUE THREAD

**Issue by Dev1an** [open-swift/S4#64]
Using DEVELOPMENT-SNAPSHOT-2016-06-06-a i get the following error:

HTTPParser-master/Packages/S4-0.9.0/Sources/Body.swift:152:21: error: closure cannot implicitly capture a mutating self parameter

**Comment by preflightsiren** [comment]
+1

**Comment by tannernelson** [comment]
Is S4 0.10, we updated it to support 06-06.
